### ISSUE TITLE
Separate BasePlugin into a seperate repository/package

### ISSUE THREAD

**Issue by clusby** [alchemyplatform/modular-account#158]
If the recommended starting point when creating a new plugin is to use BasePlugin from within the modular-account, perhaps consider separating out the plugins into a separate repository?

**Comment by adam-alchemy** [comment]
Thank you for the suggestion! We agree it would be simpler to use from a separate repo, so we contributed it to the ERC-6900 community here: https://github.com/erc6900/modular-account-libs.

We've made `BasePlugin` available, along with most libraries and interfaces you would need when creating either plugins or a modular account implementation. Please let us know if you have any other feedback.
