### ISSUE TITLE
Plugins Missing

### ISSUE THREAD

**Issue by lostcodingsomewhere** [alchemyplatform/modular-account#213]
Docs and website reference plugins like the session key plugin, but the redirect does not work properly based on website nor README.
ex: https://github.com/alchemyplatform/modular-account/blob/develop/src/plugins/session

**Comment by jaypaik** [comment]
The README is now updated links that point to the new modules that have been updated for [ERC-6900 v0.8](https://docs.google.com/document/d/1ZUSXPYtmG4GaACoQf9i7Oha7C0q-A3cCBeUBRjm20lI/edit?tab=t.0#heading=h.z6uthrv79dho). I believe the README was not updated while active development was going on, leading to the broken links. Sorry about that!

ERC-6900 v0.7 modules can still be accessed in the v1.0.x branch. The session key plugin you linked is available here: https://github.com/alchemyplatform/modular-account/tree/v1.0.x/src/plugins/session. The ERC-6900 website's links have been corrected appropriately.
