### ISSUE TITLE
Webauthn Module to be used in Modular Accounts

### ISSUE THREAD

**Issue by victormer** [alchemyplatform/modular-account#313]
Hello guys,

Is this module already available and tested for using it with Alchemy Account Kit SDK Modular Accounts?

https://github.com/alchemyplatform/modular-account/blob/8487d65ecfdea011f57026c9530d15b84c3715fb/src/modules/validation/WebAuthnValidationModule.sol#L1-L184

**Comment by howydev** [comment]
Hey @victormer - not yet, but we're working towards it! Happy to give you updates via tg if you're interested - could you ping me there? My handle is the same as on gh

Closing as this isn't an issue
